#!/usr/bin/env python3
"""Phase 3 tooling — append ALTER TABLE ADD COLUMN statements for overlap tables.

Drizzle-kit deduplicates table declarations by table name, so the
augmentation tables we declared in `schema.merged.ts` are dropped from
the generated SQL. We instead translate the SAI column definitions for
the three overlap tables (users, tasks, user_preferences) into MySQL
DDL and append them to the most recent generated migration.

Each `ALTER` is wrapped with an idempotent guard via a stored-procedure
helper `add_column_if_missing` (created at the top of the appended block).
This makes the migration safe to re-run.
"""
from __future__ import annotations
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SAI = REPO / "migrations" / "inputs" / "sai-drizzle-schema.ts"
FOUNDATION = REPO / "drizzle" / "schema.ts"
MIGRATIONS_DIR = REPO / "drizzle"
OVERLAP = ["users", "tasks", "user_preferences"]

# A minimal Drizzle-style → MySQL DDL translator for the column lines we expect.
TYPE_PATTERNS = [
    (re.compile(r'\bvarchar\("([^"]+)",\s*\{\s*length:\s*(\d+)\s*\}\)'), lambda m: (m.group(1), f"varchar({m.group(2)})")),
    (re.compile(r'\btext\("([^"]+)"\)'), lambda m: (m.group(1), "text")),
    (re.compile(r'\bint\("([^"]+)"\)'), lambda m: (m.group(1), "int")),
    (re.compile(r'\bbigint\("([^"]+)",\s*\{[^}]*\}\)'), lambda m: (m.group(1), "bigint")),
    (re.compile(r'\bbigint\("([^"]+)"\)'), lambda m: (m.group(1), "bigint")),
    (re.compile(r'\btimestamp\("([^"]+)"\)'), lambda m: (m.group(1), "timestamp NULL")),
    (re.compile(r'\bjson\("([^"]+)"\)'), lambda m: (m.group(1), "json")),
    (re.compile(r'\bdate\("([^"]+)"\)'), lambda m: (m.group(1), "date")),
    (re.compile(r'\bfloat\("([^"]+)"\)'), lambda m: (m.group(1), "float")),
    (re.compile(r'\bdouble\("([^"]+)"\)'), lambda m: (m.group(1), "double")),
    (re.compile(r'\bdecimal\("([^"]+)",\s*\{\s*precision:\s*(\d+),\s*scale:\s*(\d+)\s*\}\)'),
        lambda m: (m.group(1), f"decimal({m.group(2)},{m.group(3)})")),
    (re.compile(r'\bmysqlBoolean\("([^"]+)"\)|\bboolean\("([^"]+)"\)'),
        lambda m: ((m.group(1) or m.group(2)), "boolean")),
    (re.compile(r'\bmysqlEnum\("([^"]+)",\s*\[([^\]]+)\]\)'),
        lambda m: (m.group(1), f"enum({m.group(2).strip()})")),
]


def parse_table_columns(text: str, db_name: str) -> tuple[str, list[tuple[str, str, str]]]:
    """Returns (export_const, [(sql_col, sql_type, mods)]) from a TS table block."""
    m = re.search(rf'export const (\w+) = mysqlTable\("{re.escape(db_name)}"\s*,\s*\{{', text)
    if not m:
        return ("", [])
    body_start = m.end()
    body = text[body_start:]
    sep = re.search(r'\n\}\s*,\s*\(table\)\s*=>', body)
    end_simple = re.search(r'\n\}\);\s*\n', body)
    if sep and (not end_simple or sep.start() < end_simple.start()):
        body = body[: sep.start()]
    elif end_simple:
        body = body[: end_simple.start()]
    cols: list[tuple[str, str, str]] = []
    for line in body.splitlines():
        line_stripped = line.strip()
        if not line_stripped or line_stripped.startswith("//") or line_stripped.startswith("/*") or line_stripped.startswith("*"):
            continue
        sql_col = None
        sql_type = None
        for pat, fn in TYPE_PATTERNS:
            mm = pat.search(line)
            if mm:
                sql_col, sql_type = fn(mm)
                break
        if not sql_col:
            continue
        mods = []
        if ".notNull()" in line:
            mods.append("NOT NULL")
        # default literal (.default(...))
        dm = re.search(r'\.default\(([^)]+)\)', line)
        if dm:
            val = dm.group(1).strip()
            if val.startswith('"') or val.startswith("'") or val in ("true", "false") or val.replace(".", "").replace("-", "").isdigit():
                mods.append(f"DEFAULT {val}")
            elif val == "false":
                mods.append("DEFAULT false")
        if ".defaultNow()" in line:
            mods.append("DEFAULT (now())")
        if ".onUpdateNow()" in line:
            mods.append("ON UPDATE CURRENT_TIMESTAMP")
        cols.append((sql_col, sql_type, " ".join(mods)))
    return (m.group(1), cols)


def latest_migration() -> Path:
    files = sorted([p for p in MIGRATIONS_DIR.glob("*.sql") if p.name[0].isdigit()])
    return files[-1]


def main() -> None:
    sai = SAI.read_text()
    found = FOUNDATION.read_text()
    target = latest_migration()
    out_lines: list[str] = []
    out_lines.append("\n--> statement-breakpoint\n")
    out_lines.append("-- Stewardly v3 overlap-table column additions (additive only)\n")
    out_lines.append("-- Generated by migrations/scripts/04_emit_overlap_alters.py\n")
    # Idempotent helper procedure
    out_lines.append("""DROP PROCEDURE IF EXISTS sw_add_column_if_missing;
--> statement-breakpoint
CREATE PROCEDURE sw_add_column_if_missing(
  IN tbl VARCHAR(64),
  IN col VARCHAR(64),
  IN ddl TEXT
)
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = tbl
      AND column_name = col
  ) THEN
    SET @stmt = CONCAT('ALTER TABLE `', tbl, '` ADD COLUMN ', ddl);
    PREPARE p FROM @stmt; EXECUTE p; DEALLOCATE PREPARE p;
  END IF;
END;
--> statement-breakpoint
""")
    total_added = 0
    for table in OVERLAP:
        _, found_cols = parse_table_columns(found, table)
        _, sai_cols = parse_table_columns(sai, table)
        found_names = {c[0] for c in found_cols}
        new = [c for c in sai_cols if c[0] not in found_names]
        out_lines.append(f"-- {table}: {len(new)} new column(s)\n")
        for col, ty, mods in new:
            ddl = f"`{col}` {ty}"
            if mods:
                ddl += " " + mods
            ddl_escaped = ddl.replace("'", "''")
            out_lines.append(
                f"CALL sw_add_column_if_missing('{table}', '{col}', '{ddl_escaped}');\n--> statement-breakpoint\n"
            )
            total_added += 1
        out_lines.append("\n")
    out_lines.append("DROP PROCEDURE IF EXISTS sw_add_column_if_missing;\n--> statement-breakpoint\n")
    with target.open("a") as f:
        f.writelines(out_lines)
    print(f"Appended {total_added} ALTER calls to {target.name}")


if __name__ == "__main__":
    main()
