/**
 * DesktopAppPage — Desktop App Builder with Build Queue
 * Capability #46: Desktop App
 *
 * Generates Tauri configuration and build scripts to package
 * the web app as a native desktop application. Includes server-backed
 * build queue, build history, and status tracking.
 */
import { useState, useCallback, useMemo } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { getLoginUrl } from "@/const";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Monitor, Download, Copy, CheckCircle2, Loader2, LogIn,
  ArrowLeft, Settings, Package, Apple, Laptop, History,
  Play, Clock, AlertCircle, RefreshCw, Trash2,
} from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { motion, AnimatePresence } from "framer-motion";
import HeroIllustration from "@/components/HeroIllustration";

type Platform = "windows" | "macos" | "linux";

interface BuildRecord {
  id: number;
  appName: string;
  appId: string;
  version: string;
  platforms: string;
  status: string;
  createdAt: number;
  completedAt?: number | null;
  buildLog?: string | null;
  artifactUrl?: string | null;
}

export default function DesktopAppPage() {
  const { isAuthenticated } = useAuth();
  const [, navigate] = useLocation();
  const [appName, setAppName] = useState("Stewardly");
  const [appId, setAppId] = useState("com.manus.next");
  const [version, setVersion] = useState("1.0.0");
  const [platforms, setPlatforms] = useState<Platform[]>(["windows", "macos", "linux"]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedConfig, setGeneratedConfig] = useState<string | null>(null);
  const [generatedScript, setGeneratedScript] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState("configure");

  // Build history from server
  const buildsQuery = trpc.appPublish.userBuilds.useQuery(undefined, {
    staleTime: 30_000,
    enabled: isAuthenticated,
    retry: false,
  });

  const createBuildMutation = trpc.appPublish.createBuild.useMutation({
    onSuccess: () => {
      toast.success("Build queued successfully!");
      buildsQuery.refetch();
      setActiveTab("history");
    },
    onError: (err) => { toast.error(`Build failed: ${err.message}`); },
  });

  const builds = useMemo(() => {
    if (!buildsQuery.data) return [];
    const items = Array.isArray(buildsQuery.data) ? buildsQuery.data : (buildsQuery.data as any)?.items ?? [];
    return items as BuildRecord[];
  }, [buildsQuery.data]);

  const togglePlatform = useCallback((p: Platform) => {
    setPlatforms((prev) =>
      prev.includes(p) ? prev.filter((x) => x !== p) : [...prev, p]
    );
  }, []);

  const generateConfig = useCallback(async () => {
    if (!appName.trim()) {
      toast.error("Enter an app name");
      return;
    }
    setIsGenerating(true);

    const tauriConfig = JSON.stringify({
      "$schema": "../node_modules/@tauri-apps/cli/schema.json",
      build: {
        beforeBuildCommand: "pnpm build",
        beforeDevCommand: "pnpm dev",
        devPath: "http://localhost:5173",
        distDir: "../dist",
      },
      package: { productName: appName, version },
      tauri: {
        allowlist: {
          all: false,
          shell: { all: false, open: true },
          dialog: { all: true },
          fs: { all: true, scope: ["$APPDATA/**", "$DOWNLOAD/**"] },
          http: { all: true, scope: ["https://**"] },
          notification: { all: true },
          clipboard: { all: true },
        },
        bundle: {
          active: true,
          identifier: appId,
          icon: ["icons/32x32.png", "icons/128x128.png", "icons/128x128@2x.png", "icons/icon.icns", "icons/icon.ico"],
          targets: platforms.includes("windows")
            ? ["nsis", "msi"]
            : platforms.includes("macos")
            ? ["dmg", "app"]
            : ["deb", "appimage"],
        },
        security: { csp: null },
        windows: [{
          fullscreen: false, resizable: true, title: appName,
          width: 1200, height: 800, minWidth: 800, minHeight: 600,
        }],
      },
    }, null, 2);

    const buildScript = `#!/bin/bash
# ${appName} Desktop Build Script — Generated by Manus
set -e
echo "=== ${appName} Desktop Build ==="
echo "Version: ${version}"
echo "Platforms: ${platforms.join(", ")}"

# Prerequisites check
command -v cargo >/dev/null 2>&1 || { echo "Rust/Cargo required. Install from https://rustup.rs"; exit 1; }
command -v pnpm >/dev/null 2>&1 || { echo "pnpm required. Install with: npm i -g pnpm"; exit 1; }

# Install Tauri CLI
pnpm add -D @tauri-apps/cli @tauri-apps/api

# Initialize Tauri (if not already)
if [ ! -d "src-tauri" ]; then
  pnpm tauri init
fi

# Copy generated config
cp tauri.conf.json src-tauri/tauri.conf.json

# Build for each platform
${platforms.map((p) => {
  if (p === "windows") return 'echo "Building for Windows..."\npnpm tauri build --target x86_64-pc-windows-msvc';
  if (p === "macos") return 'echo "Building for macOS..."\npnpm tauri build --target aarch64-apple-darwin\npnpm tauri build --target x86_64-apple-darwin';
  return 'echo "Building for Linux..."\npnpm tauri build --target x86_64-unknown-linux-gnu';
}).join("\n\n")}

echo "=== Build complete! ==="
echo "Installers are in src-tauri/target/release/bundle/"
`;

    setGeneratedConfig(tauriConfig);
    setGeneratedScript(buildScript);
    setIsGenerating(false);
    toast.success("Desktop app configuration generated!");
  }, [appName, appId, version, platforms]);

  const queueBuild = useCallback(() => {
    createBuildMutation.mutate({
      platform: "web_pwa" as const,
      buildMethod: "pwa_manifest" as const,
      mobileProjectId: 0,
      version: version,
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps -- .mutate is stable (tRPC)
  }, [platforms, createBuildMutation.mutate]);

  const copyToClipboard = useCallback((text: string, label: string) => {
    navigator.clipboard.writeText(text);
    toast.success(`${label} copied to clipboard`);
  }, []);

  const downloadConfig = useCallback(() => {
    if (!generatedConfig) return;
    const blob = new Blob([generatedConfig], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "tauri.conf.json";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Configuration downloaded");
  }, [generatedConfig]);

  if (!isAuthenticated) {
    return (
      <div className="h-full flex items-center justify-center">
        <Card className="max-w-sm">
          <CardContent className="p-6 text-center">
            <Monitor className="w-12 h-12 text-primary mx-auto mb-4" />
            <h2 className="text-lg font-semibold mb-2">Desktop App Builder</h2>
            <p className="text-muted-foreground mb-4">Sign in to build desktop apps.</p>
            <Button onClick={() => (window.location.href = getLoginUrl())}>
              <LogIn className="w-4 h-4 mr-2" /> Sign In
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto">
      <div className="max-w-5xl mx-auto px-4 py-6">
        <div className="flex items-center gap-2 mb-4">
          <Button variant="ghost" size="icon" onClick={() => navigate("/")} aria-label="Go back">
            <ArrowLeft className="w-4 h-4" />
          </Button>
          {builds.length > 0 && (
            <Badge variant="secondary" className="text-[10px] ml-auto">
              {builds.filter((b) => b.status === "completed").length}/{builds.length} builds
            </Badge>
          )}
        </div>
        <HeroIllustration
          type="hero-desktop"
          title="Desktop App Builder"
          subtitle="Package your web app as a native desktop application"
          icon={<Monitor className="w-5 h-5 text-primary" />}
        />

        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="mb-6">
            <TabsTrigger value="configure" className="gap-1.5">
              <Settings className="w-3.5 h-3.5" /> Configure
            </TabsTrigger>
            <TabsTrigger value="output" disabled={!generatedConfig} className="gap-1.5">
              <Package className="w-3.5 h-3.5" /> Output
            </TabsTrigger>
            <TabsTrigger value="history" className="gap-1.5">
              <History className="w-3.5 h-3.5" /> Build Queue
              {builds.filter((b) => b.status === "building" || b.status === "queued").length > 0 && (
                <span className="ml-1 w-2 h-2 rounded-full bg-primary animate-pulse" />
              )}
            </TabsTrigger>
          </TabsList>

          {/* Configure Tab */}
          <TabsContent value="configure">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="space-y-4">
                <Card className="bg-card border-border">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm flex items-center gap-2">
                      <Settings className="w-4 h-4 text-primary" /> App Configuration
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div>
                      <label className="text-xs text-muted-foreground mb-1 block">App Name</label>
                      <Input value={appName} onChange={(e) => setAppName(e.target.value)} />
                    </div>
                    <div>
                      <label className="text-xs text-muted-foreground mb-1 block">Bundle ID</label>
                      <Input value={appId} onChange={(e) => setAppId(e.target.value)} />
                    </div>
                    <div>
                      <label className="text-xs text-muted-foreground mb-1 block">Version</label>
                      <Input value={version} onChange={(e) => setVersion(e.target.value)} />
                    </div>
                  </CardContent>
                </Card>

                <Card className="bg-card border-border">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm flex items-center gap-2">
                      <Package className="w-4 h-4 text-primary" /> Target Platforms
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="flex gap-3">
                      {([
                        { id: "windows" as Platform, label: "Windows", icon: Laptop },
                        { id: "macos" as Platform, label: "macOS", icon: Apple },
                        { id: "linux" as Platform, label: "Linux", icon: Monitor },
                      ]).map((p) => (
                        <button
                          key={p.id}
                          onClick={() => togglePlatform(p.id)}
                          className={cn(
                            "flex-1 flex flex-col items-center gap-2 p-4 rounded-xl border transition-all",
                            platforms.includes(p.id)
                              ? "border-primary bg-primary/5"
                              : "border-border hover:border-primary/30"
                          )}
                        >
                          <p.icon className={cn("w-6 h-6", platforms.includes(p.id) ? "text-primary" : "text-muted-foreground")} />
                          <span className="text-xs font-medium">{p.label}</span>
                          {platforms.includes(p.id) && <CheckCircle2 className="w-3.5 h-3.5 text-primary" />}
                        </button>
                      ))}
                    </div>
                    <div className="flex gap-2 mt-4">
                      <Button onClick={generateConfig} disabled={isGenerating || platforms.length === 0} className="flex-1">
                        {isGenerating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Package className="w-4 h-4 mr-2" />}
                        Generate Config
                      </Button>
                      <Button
                        variant="outline"
                        onClick={queueBuild}
                        disabled={createBuildMutation.isPending || platforms.length === 0}
                        className="gap-1.5"
                      >
                        {createBuildMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
                        Queue Build
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* Quick Stats */}
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { label: "Total Builds", value: builds.length, icon: Package, color: "text-primary" },
                    { label: "Completed", value: builds.filter((b) => b.status === "completed").length, icon: CheckCircle2, color: "text-muted-foreground" },
                    { label: "In Queue", value: builds.filter((b) => b.status === "queued" || b.status === "building").length, icon: Clock, color: "text-foreground" },
                    { label: "Failed", value: builds.filter((b) => b.status === "failed").length, icon: AlertCircle, color: "text-red-400" },
                  ].map((stat) => (
                    <motion.div
                      key={stat.label}
                      initial={{ opacity: 0, y: 8 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="bg-card border border-border rounded-xl p-4"
                    >
                      <div className="flex items-center gap-2 mb-1">
                        <stat.icon className={cn("w-3.5 h-3.5", stat.color)} />
                        <span className="text-[10px] text-muted-foreground">{stat.label}</span>
                      </div>
                      <p className="text-xl font-semibold text-foreground tabular-nums">{stat.value}</p>
                    </motion.div>
                  ))}
                </div>

                <Card className="bg-card border-border">
                  <CardContent className="p-4">
                    <h3 className="text-sm font-medium text-foreground mb-3">Supported Targets</h3>
                    <div className="space-y-2 text-xs text-muted-foreground">
                      <div className="flex items-center gap-2">
                        <Laptop className="w-3.5 h-3.5" />
                        <span>Windows: NSIS installer, MSI package</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <Apple className="w-3.5 h-3.5" />
                        <span>macOS: DMG image, .app bundle (ARM + Intel)</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <Monitor className="w-3.5 h-3.5" />
                        <span>Linux: DEB package, AppImage</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </TabsContent>

          {/* Output Tab */}
          <TabsContent value="output">
            {generatedConfig && generatedScript && (
              <div className="space-y-4">
                <Card className="bg-card border-border">
                  <CardHeader className="pb-3">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-sm">tauri.conf.json</CardTitle>
                      <div className="flex gap-1">
                        <Button variant="ghost" size="sm" onClick={() => copyToClipboard(generatedConfig, "Config")}>
                          <Copy className="w-3 h-3 mr-1" /> Copy
                        </Button>
                        <Button variant="ghost" size="sm" onClick={downloadConfig}>
                          <Download className="w-3 h-3 mr-1" /> Download
                        </Button>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <pre className="bg-muted/50 rounded-lg p-3 text-xs overflow-x-auto max-h-60 overflow-y-auto">
                      <code>{generatedConfig}</code>
                    </pre>
                  </CardContent>
                </Card>

                <Card className="bg-card border-border">
                  <CardHeader className="pb-3">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-sm">build.sh</CardTitle>
                      <Button variant="ghost" size="sm" onClick={() => copyToClipboard(generatedScript, "Build script")}>
                        <Copy className="w-3 h-3 mr-1" /> Copy
                      </Button>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <pre className="bg-muted/50 rounded-lg p-3 text-xs overflow-x-auto max-h-60 overflow-y-auto">
                      <code>{generatedScript}</code>
                    </pre>
                  </CardContent>
                </Card>
              </div>
            )}
          </TabsContent>

          {/* Build Queue Tab */}
          <TabsContent value="history">
            <div className="space-y-3">
              <div className="flex items-center justify-between mb-2">
                <h3 className="text-sm font-medium text-foreground">Build History</h3>
                <Button variant="ghost" size="sm" onClick={() => buildsQuery.refetch()} className="gap-1.5">
                  <RefreshCw className={cn("w-3.5 h-3.5", buildsQuery.isFetching && "animate-spin")} />
                  Refresh
                </Button>
              </div>

              {buildsQuery.isLoading ? (
                <Card className="bg-card border-border">
                  <CardContent className="p-8 text-center">
                    <Loader2 className="w-6 h-6 text-primary animate-spin mx-auto" />
                  </CardContent>
                </Card>
              ) : builds.length === 0 ? (
                <Card className="bg-card border-border">
                  <CardContent className="p-8 text-center">
                    <History className="w-10 h-10 text-muted-foreground mx-auto mb-3" />
                    <p className="text-sm text-muted-foreground">No builds yet. Configure and queue your first build.</p>
                  </CardContent>
                </Card>
              ) : (
                <AnimatePresence>
                  {builds.map((build, i) => (
                    <motion.div
                      key={build.id}
                      initial={{ opacity: 0, y: 8 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: i * 0.03 }}
                    >
                      <Card className="bg-card border-border">
                        <CardContent className="p-4">
                          <div className="flex items-center justify-between">
                            <div className="flex items-center gap-3 min-w-0">
                              <div className={cn(
                                "w-8 h-8 rounded-lg flex items-center justify-center shrink-0",
                                build.status === "completed" ? "bg-primary/10" :
                                build.status === "building" ? "bg-blue-500/10" :
                                build.status === "failed" ? "bg-red-500/10" :
                                "bg-muted"
                              )}>
                                {build.status === "completed" ? <CheckCircle2 className="w-4 h-4 text-primary" /> :
                                 build.status === "building" ? <Loader2 className="w-4 h-4 text-blue-400 animate-spin" /> :
                                 build.status === "failed" ? <AlertCircle className="w-4 h-4 text-red-400" /> :
                                 <Clock className="w-4 h-4 text-muted-foreground" />}
                              </div>
                              <div className="min-w-0">
                                <p className="text-sm font-medium text-foreground truncate">
                                  Build #{build.id}
                                </p>
                                <p className="text-[10px] text-muted-foreground">
                                  {new Date(build.createdAt).toLocaleString()} · {build.platforms || "multi-platform"}
                                </p>
                              </div>
                            </div>
                            <div className="flex items-center gap-2 shrink-0">
                              <Badge
                                variant="secondary"
                                className={cn(
                                  "text-[10px]",
                                  build.status === "completed" && "bg-primary/10 text-primary",
                                  build.status === "building" && "bg-blue-500/10 text-blue-400",
                                  build.status === "failed" && "bg-red-500/10 text-red-400",
                                )}
                              >
                                {build.status}
                              </Badge>
                              {build.artifactUrl && (
                                <Button variant="ghost" size="sm" asChild>
                                  <a href={build.artifactUrl} target="_blank" rel="noopener noreferrer">
                                    <Download className="w-3.5 h-3.5" />
                                  </a>
                                </Button>
                              )}
                            </div>
                          </div>
                          {build.buildLog && (
                            <pre className="mt-3 bg-muted/30 rounded-lg p-2 text-[10px] text-muted-foreground max-h-24 overflow-y-auto">
                              {build.buildLog}
                            </pre>
                          )}
                        </CardContent>
                      </Card>
                    </motion.div>
                  ))}
                </AnimatePresence>
              )}
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
