// AUTO-GENERATED by scripts/regen-routers.mjs — every router under server/routers/ is mounted.
// Run `node scripts/regen-routers.mjs` after adding a new router file.

import { addendumFeaturesRouter } from "./routers/addendumFeatures";
import { adminRouter } from "./routers/admin";
import { adminAdoptionRouter } from "./routers/adminAdoption";
import { adminIntelligenceRouter } from "./routers/adminIntelligence";
import { advancedIntelligenceRouter } from "./routers/advancedIntelligence";
import { aegisRouter } from "./routers/aegis";
import { agenticRouter } from "./routers/agenticExecution";
import { aiAutonomyRouter } from "./routers/aiAutonomy";
import { aiLayersRouter } from "./routers/aiLayers";
import { aiPlatformRouter } from "./routers/aiPlatform";
import { analyticsRouter } from "./routers/analytics";
import { anonymousChatRouter } from "./routers/anonymousChat";
import { appPublishRouter } from "./routers/appPublish";
import { appsRouter } from "./routers/apps";
import { atlasRouter } from "./routers/atlas";
import { audioRouter } from "./routers/audio";
import { authEnrichmentRouter } from "./routers/authEnrichment";
import { automationRouter } from "./routers/automation";
import { autonomousProcessingRouter } from "./routers/autonomousProcessing";
import { branchesRouter } from "./routers/branches";
import { bridgeRouter } from "./routers/bridge";
import { browserRouter } from "./routers/browser";
import { browserAutomationRouter } from "./routers/browserAutomation";
import { cacheRouter } from "./routers/cache";
import { cadenceEngineRouter } from "./routers/cadenceEngine";
import { calcSessionRouter } from "./routers/calcSession";
import { calculatorEngineRouter } from "./routers/calculatorEngine";
import { clientRouter } from "./routers/client";
import { codeChatRouter } from "./routers/codeChat";
import { communityRouter } from "./routers/community";
import { comparablesRouter } from "./routers/comparables";
import { complianceRouter } from "./routers/compliance";
import { complianceGovernanceRouter } from "./routers/complianceGovernance";
import { connectorRouter } from "./routers/connector";
import { consentRouter } from "./routers/consent";
import { contentRouter } from "./routers/contentRouter";
import { dataAnalysisRouter } from "./routers/dataAnalysis";
import { dataIngestionRouter } from "./routers/dataIngestion";
import { dataIngestionEnhancedRouter } from "./routers/dataIngestionEnhanced";
import { dataSeedRouter } from "./routers/dataSeed";
import { designRouter } from "./routers/design";
import { deviceRouter } from "./routers/device";
import { documentRouter } from "./routers/document";
import { dripifyWebhookRouter } from "./routers/dripifyWebhook";
import { dynamicIntegrationsRouter } from "./routers/dynamicIntegrations";
import { emailAuthRouter } from "./routers/emailAuth";
import { emailCampaignRouter } from "./routers/emailCampaign";
import { embedsRouter } from "./routers/embeds";
import { enginesRouter } from "./routers/engines";
import { enrichmentEngineRouter } from "./routers/enrichmentEngine";
import { estateRouter } from "./routers/estate";
import { exponentialEngineRouter } from "./routers/exponentialEngine";
import { exportsRouter } from "./routers/exports";
import { fairnessRouter } from "./routers/fairness";
import { featureFlagsRouter } from "./routers/featureFlags";
import { feedbackRouter } from "./routers/feedback";
import { fileRouter } from "./routers/file";
import { fileProcessingRouter } from "./routers/fileProcessing";
import { finalOrphansRouter } from "./routers/finalOrphans";
import { financialDataRouter } from "./routers/financialData";
import { financialInstrumentsRouter } from "./routers/financialInstruments";
import { financialProfileRouter } from "./routers/financialProfile";
import { gdprRouter } from "./routers/gdpr";
import { ghlWebhookRouter } from "./routers/ghlWebhook";
import { githubRouter } from "./routers/github";
import { hubRouter } from "./routers/hub";
import { hubAllocationsRouter } from "./routers/hubAllocations";
import { hubHistoryRouter } from "./routers/hubHistory";
import { illustrationsRouter } from "./routers/illustrations";
import { importRouter } from "./routers/importRouter";
import { improvementEngineRouter } from "./routers/improvementEngine";
import { insightsRouter } from "./routers/insights";
import { integrationsRouter } from "./routers/integrations";
import { intelligenceEngineRouter } from "./routers/intelligenceEngine";
import { kbAccessRouter } from "./routers/kbAccess";
import { knowledgeBaseRouter } from "./routers/knowledgeBase";
import { knowledgeGraphRouter } from "./routers/knowledgeGraph";
import { leadCaptureRouter } from "./routers/leadCapture";
import { leadPipelineRouter } from "./routers/leadPipeline";
import { learningRouter } from "./routers/learning";
import { achievementsRouter, aiQuizRouter, audioProgressRouter, bookmarksRouter, challengesRouter, discoveryRouter, groupMasteryRouter, groupsRouter, learningSocialRouter, playlistsRouter, settingsRouter, sharedQuizzesRouter, studySessionsRouter } from "./routers/learningSocial";
import { libraryRouter } from "./routers/library";
import { llmRouter } from "./routers/llm";
import { marketRouter } from "./routers/market";
import { matchingRouter } from "./routers/matching";
import { maxScoresRouter } from "./routers/maxScores";
import { meetingRouter } from "./routers/meeting";
import { meetingsRouter } from "./routers/meetings";
import { memoryRouter } from "./routers/memory";
import { mobileProjectRouter } from "./routers/mobileProject";
import { modelEngineRouter } from "./routers/modelEngine";
import { multiModalProcessingRouter } from "./routers/multiModalProcessing";
import { multiModelRouter } from "./routers/multiModel";
import { musicRouter } from "./routers/music";
import { myContentRouter } from "./routers/myContent";
import { notificationRouter } from "./routers/notification";
import { notificationsRouter } from "./routers/notifications";
import { ogImageRouter } from "./routers/ogImage";
import { openClawRouter } from "./routers/openClaw";
import { operationsRouter } from "./routers/operations";
import { orchestrationRouter } from "./routers/orchestration";
import { orgBrandingRouter } from "./routers/orgBranding";
import { organizationsRouter } from "./routers/organizations";
import { passiveActionsRouter } from "./routers/passiveActions";
import { paymentRouter } from "./routers/payment";
import { personalizationRouter } from "./routers/personalization";
import { pfrReportRouter } from "./routers/pfrReport";
import { pipelineRouter } from "./routers/pipeline";
import { plaidRouter } from "./routers/plaid";
import { planSharingRouter } from "./routers/planSharing";
import { planningRouter } from "./routers/planning";
import { planningHierarchyRouter } from "./routers/planningHierarchy";
import { portalRouter } from "./routers/portal";
import { portfolioLedgerRouter } from "./routers/portfolioLedger";
import { preferencesRouter } from "./routers/preferences";
import { premiumFinanceRouter } from "./routers/premiumFinanceRouter";
import { processImprovementRouter } from "./routers/processImprovement";
import { productIntelligenceRouter } from "./routers/productIntelligence";
import { productsRouter } from "./routers/products";
import { capabilitiesRouter, coiRouter, commsRouter, compensationRouter, contextRouter, documentsRouter, engagementRouter, metricsRouter, professionalPracticeRouter, reviewsRouter, segmentsRouter } from "./routers/professionalPractice";
import { professionalsRouter } from "./routers/professionals";
import { projectRouter } from "./routers/project";
import { propagationRouter } from "./routers/propagation";
import { propensityRouter } from "./routers/propensity";
import { rebalancingRouter } from "./routers/rebalancing";
import { recommendationRouter } from "./routers/recommendation";
import { referralsRouter } from "./routers/referrals";
import { relationshipsRouter } from "./routers/relationships";
import { remainingOrphansRouter } from "./routers/remainingOrphans";
import { replayRouter } from "./routers/replay";
import { reportsRouter } from "./routers/reports";
import { reportsFiduciaryRouter } from "./routers/reportsFiduciary";
import { reportsBusinessRouter } from "./routers/reportsRouter";
import { researchRouter } from "./routers/research";
import { rolesRouter } from "./routers/roles";
import { scenarioExportRouter } from "./routers/scenarioExport";
import { scenariosRouter } from "./routers/scenarios";
import { scheduleRouter } from "./routers/schedule";
import { scheduledIngestionRouter } from "./routers/scheduledIngestion";
import { searchEnhancedRouter } from "./routers/searchEnhanced";
import { securityPrivacyRouter } from "./routers/securityPrivacy";
import { selfDiscoveryRouter } from "./routers/selfDiscovery";
import { creditBureauRouter, crmRouter, esignatureRouter, pdfRouter } from "./routers/serviceRouters";
import { shareRouter } from "./routers/share";
import { sharingRouter } from "./routers/sharing";
import { skillRouter } from "./routers/skill";
import { slidesRouter } from "./routers/slides";
import { smsitWebhookRouter } from "./routers/smsitWebhook";
import { snapTradeRouter } from "./routers/snapTrade";
import { sovereignRouter } from "./routers/sovereign";
import { sovereignSyncRouter } from "./routers/sovereignSync";
import { householdsRouter, managerAiRouter, organizationAiRouter, platformAiRouter, professionalAiRouter } from "./routers/stewardlySettings";
import { suitabilityEngineRouter } from "./routers/suitabilityEngine";
import { systemHealthRouter } from "./routers/systemHealth";
import { taskRouter } from "./routers/task";
import { taxRouter } from "./routers/tax";
import { teamRouter } from "./routers/team";
import { templatesRouter } from "./routers/templates";
import { usageRouter } from "./routers/usage";
import { usageAnalyticsRouter } from "./routers/usageAnalytics";
import { coiRouter, complianceCopilotRouter, digitalAssetsRouter, educationRouter, equityCompRouter, knowledgeGraphRouter, memoryEpisodesRouter, studentLoansRouter } from "./routers/v4Features";
import { ambientRouter, annualReviewRouter, businessExitRouter, clientSegmentationRouter, constitutionalRouter, financialHealthRouter, ltcPlannerRouter, planAdherenceRouter, portalOptimizerRouter, practiceIntelligenceRouter, workflowOrchestratorRouter } from "./routers/v5Features";
import { charitableRouter, commsRouter, divorceRouter, educationPlannerRouter, feeBillingRouter, hsaOptimizerRouter, medicareRouter, ssOptimizerRouter, taskEngineRouter, taxProjectorRouter } from "./routers/v6Features";
import { verificationRouter } from "./routers/verification";
import { videoRouter } from "./routers/video";
import { videoConferencingRouter } from "./routers/videoConferencing";
import { videoWorkerRouter } from "./routers/videoWorker";
import { voiceRouter } from "./routers/voice";
import { voiceAgentRouter } from "./routers/voiceAgent";
import { wealthEngineRouter } from "./routers/wealthEngine";
import { webappRouter } from "./routers/webapp";
import { webappProjectRouter } from "./routers/webappProject";
import { webhookIngestionRouter } from "./routers/webhookIngestion";
import { workflowRouter } from "./routers/workflow";
import { workflowAutomationRouter } from "./routers/workflowAutomation";
import { workspaceRouter } from "./routers/workspace";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, router } from "./_core/trpc";

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  achievements: achievementsRouter,
  addendumFeatures: addendumFeaturesRouter,
  admin: adminRouter,
  adminAdoption: adminAdoptionRouter,
  adminIntelligence: adminIntelligenceRouter,
  advancedIntelligence: advancedIntelligenceRouter,
  aegis: aegisRouter,
  agentic: agenticRouter,
  aiAutonomy: aiAutonomyRouter,
  aiLayers: aiLayersRouter,
  aiPlatform: aiPlatformRouter,
  aiQuiz: aiQuizRouter,
  ambient: ambientRouter,
  analytics: analyticsRouter,
  annualReview: annualReviewRouter,
  anonymousChat: anonymousChatRouter,
  appPublish: appPublishRouter,
  apps: appsRouter,
  atlas: atlasRouter,
  audio: audioRouter,
  audioProgress: audioProgressRouter,
  authEnrichment: authEnrichmentRouter,
  automation: automationRouter,
  autonomousProcessing: autonomousProcessingRouter,
  bookmarks: bookmarksRouter,
  branches: branchesRouter,
  bridge: bridgeRouter,
  browser: browserRouter,
  browserAutomation: browserAutomationRouter,
  businessExit: businessExitRouter,
  cache: cacheRouter,
  cadenceEngine: cadenceEngineRouter,
  calcSession: calcSessionRouter,
  calculatorEngine: calculatorEngineRouter,
  capabilities: capabilitiesRouter,
  challenges: challengesRouter,
  charitable: charitableRouter,
  client: clientRouter,
  clientSegmentation: clientSegmentationRouter,
  codeChat: codeChatRouter,
  // R14.19.step1: agentExecutor alias — same router exposed under a new
  // canonical name. The old `codeChat` key stays until step3 finishes the
  // frontend migration in client/src/components/consensus/ComparisonView.tsx.
  agentExecutor: codeChatRouter,
  coi: coiRouter,
  coi2: coiRouter,
  comms: commsRouter,
  comms2: commsRouter,
  community: communityRouter,
  comparables: comparablesRouter,
  compensation: compensationRouter,
  compliance: complianceRouter,
  complianceCopilot: complianceCopilotRouter,
  complianceGovernance: complianceGovernanceRouter,
  connector: connectorRouter,
  consent: consentRouter,
  constitutional: constitutionalRouter,
  content: contentRouter,
  context: contextRouter,
  creditBureau: creditBureauRouter,
  crm: crmRouter,
  dataAnalysis: dataAnalysisRouter,
  dataIngestion: dataIngestionRouter,
  dataIngestionEnhanced: dataIngestionEnhancedRouter,
  dataSeed: dataSeedRouter,
  design: designRouter,
  device: deviceRouter,
  digitalAssets: digitalAssetsRouter,
  discovery: discoveryRouter,
  divorce: divorceRouter,
  document: documentRouter,
  documents: documentsRouter,
  dripifyWebhook: dripifyWebhookRouter,
  dynamicIntegrations: dynamicIntegrationsRouter,
  education: educationRouter,
  educationPlanner: educationPlannerRouter,
  emailAuth: emailAuthRouter,
  emailCampaign: emailCampaignRouter,
  embeds: embedsRouter,
  engagement: engagementRouter,
  engines: enginesRouter,
  enrichmentEngine: enrichmentEngineRouter,
  equityComp: equityCompRouter,
  esignature: esignatureRouter,
  estate: estateRouter,
  exponentialEngine: exponentialEngineRouter,
  exports: exportsRouter,
  fairness: fairnessRouter,
  featureFlags: featureFlagsRouter,
  feeBilling: feeBillingRouter,
  feedback: feedbackRouter,
  file: fileRouter,
  fileProcessing: fileProcessingRouter,
  finalOrphans: finalOrphansRouter,
  financialData: financialDataRouter,
  financialHealth: financialHealthRouter,
  financialInstruments: financialInstrumentsRouter,
  financialProfile: financialProfileRouter,
  gdpr: gdprRouter,
  ghlWebhook: ghlWebhookRouter,
  github: githubRouter,
  groupMastery: groupMasteryRouter,
  groups: groupsRouter,
  households: householdsRouter,
  hsaOptimizer: hsaOptimizerRouter,
  hub: hubRouter,
  hubAllocations: hubAllocationsRouter,
  hubHistory: hubHistoryRouter,
  illustrations: illustrationsRouter,
  import: importRouter,
  improvementEngine: improvementEngineRouter,
  insights: insightsRouter,
  integrations: integrationsRouter,
  intelligenceEngine: intelligenceEngineRouter,
  kbAccess: kbAccessRouter,
  knowledgeBase: knowledgeBaseRouter,
  knowledgeGraph: knowledgeGraphRouter,
  knowledgeGraph2: knowledgeGraphRouter,
  leadCapture: leadCaptureRouter,
  leadPipeline: leadPipelineRouter,
  learning: learningRouter,
  learningSocial: learningSocialRouter,
  library: libraryRouter,
  llm: llmRouter,
  ltcPlanner: ltcPlannerRouter,
  managerAi: managerAiRouter,
  market: marketRouter,
  matching: matchingRouter,
  maxScores: maxScoresRouter,
  medicare: medicareRouter,
  meeting: meetingRouter,
  meetings: meetingsRouter,
  memory: memoryRouter,
  memoryEpisodes: memoryEpisodesRouter,
  metrics: metricsRouter,
  mobileProject: mobileProjectRouter,
  modelEngine: modelEngineRouter,
  multiModalProcessing: multiModalProcessingRouter,
  multiModel: multiModelRouter,
  music: musicRouter,
  myContent: myContentRouter,
  notification: notificationRouter,
  notifications: notificationsRouter,
  ogImage: ogImageRouter,
  openClaw: openClawRouter,
  operations: operationsRouter,
  orchestration: orchestrationRouter,
  organizationAi: organizationAiRouter,
  organizations: organizationsRouter,
  orgBranding: orgBrandingRouter,
  passiveActions: passiveActionsRouter,
  payment: paymentRouter,
  pdf: pdfRouter,
  personalization: personalizationRouter,
  pfrReport: pfrReportRouter,
  pipeline: pipelineRouter,
  plaid: plaidRouter,
  planAdherence: planAdherenceRouter,
  planning: planningRouter,
  planningHierarchy: planningHierarchyRouter,
  planSharing: planSharingRouter,
  platformAi: platformAiRouter,
  playlists: playlistsRouter,
  portal: portalRouter,
  portalOptimizer: portalOptimizerRouter,
  portfolioLedger: portfolioLedgerRouter,
  practiceIntelligence: practiceIntelligenceRouter,
  preferences: preferencesRouter,
  premiumFinance: premiumFinanceRouter,
  processImprovement: processImprovementRouter,
  productIntelligence: productIntelligenceRouter,
  products: productsRouter,
  professionalAi: professionalAiRouter,
  professionalPractice: professionalPracticeRouter,
  professionals: professionalsRouter,
  project: projectRouter,
  propagation: propagationRouter,
  propensity: propensityRouter,
  rebalancing: rebalancingRouter,
  recommendation: recommendationRouter,
  referrals: referralsRouter,
  relationships: relationshipsRouter,
  remainingOrphans: remainingOrphansRouter,
  replay: replayRouter,
  reports: reportsRouter,
  reportsBusiness: reportsBusinessRouter,
  reportsFiduciary: reportsFiduciaryRouter,
  research: researchRouter,
  reviews: reviewsRouter,
  roles: rolesRouter,
  scenarioExport: scenarioExportRouter,
  scenarios: scenariosRouter,
  schedule: scheduleRouter,
  scheduledIngestion: scheduledIngestionRouter,
  searchEnhanced: searchEnhancedRouter,
  securityPrivacy: securityPrivacyRouter,
  segments: segmentsRouter,
  selfDiscovery: selfDiscoveryRouter,
  settings: settingsRouter,
  share: shareRouter,
  sharedQuizzes: sharedQuizzesRouter,
  sharing: sharingRouter,
  skill: skillRouter,
  slides: slidesRouter,
  smsitWebhook: smsitWebhookRouter,
  snapTrade: snapTradeRouter,
  sovereign: sovereignRouter,
  sovereignSync: sovereignSyncRouter,
  ssOptimizer: ssOptimizerRouter,
  studentLoans: studentLoansRouter,
  studySessions: studySessionsRouter,
  suitabilityEngine: suitabilityEngineRouter,
  systemHealth: systemHealthRouter,
  task: taskRouter,
  taskEngine: taskEngineRouter,
  tax: taxRouter,
  taxProjector: taxProjectorRouter,
  team: teamRouter,
  templates: templatesRouter,
  usage: usageRouter,
  usageAnalytics: usageAnalyticsRouter,
  verification: verificationRouter,
  video: videoRouter,
  videoConferencing: videoConferencingRouter,
  videoWorker: videoWorkerRouter,
  voice: voiceRouter,
  voiceAgent: voiceAgentRouter,
  wealthEngine: wealthEngineRouter,
  webapp: webappRouter,
  webappProject: webappProjectRouter,
  webhookIngestion: webhookIngestionRouter,
  workflow: workflowRouter,
  workflowAutomation: workflowAutomationRouter,
  workflowOrchestrator: workflowOrchestratorRouter,
  workspace: workspaceRouter,
});

export type AppRouter = typeof appRouter;
