-- Auto-generated additive ALTERs (extracted from 0048 procedure)
-- Each is independent and idempotent (uses ADD COLUMN IF NOT EXISTS).

ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `authTier` enum("anonymous", "email", "full", "advisor_connected") NOT NULL DEFAULT "full";
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `affiliateOrgId` int;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `anonymousConversationCount` int NOT NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `passwordHash` text;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `styleProfile` text;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `suitabilityCompleted` boolean DEFAULT false;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `suitabilityData` json;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `settings` json;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `avatarUrl` text;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `tosAcceptedAt` timestamp NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `auth_provider` varchar(20) DEFAULT "manus";
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `linkedin_id` varchar(100);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `google_id` varchar(100);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `linkedin_profile_url` varchar(500);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `linkedin_headline` varchar(300);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `linkedin_industry` varchar(100);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `linkedin_location` varchar(200);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `google_phone` varchar(50);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `google_birthday` timestamp NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `google_gender` varchar(20);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `google_address_json` json;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `google_organizations_json` json;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `employer_name` varchar(200);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `job_title` varchar(200);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `profile_enriched_at` timestamp NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `profile_enrichment_source` varchar(50);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `sign_in_data_json` json;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `stripe_customer_id` varchar(255);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `stripe_subscription_id` varchar(255);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `stripe_plan_id` varchar(255);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `stripe_subscription_status` varchar(50);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `stripe_current_period_end` timestamp NULL;
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `user_id` int NOT NULL;
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `assigned_to` int;
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `client_id` int;
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `description` text;
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `category` enum("client_review", "compliance", "onboarding", "follow_up", "planning", "admin", "meeting_prep", "document", "other") DEFAULT "other";
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `due_date` timestamp NULL;
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `completed_at` timestamp NULL;
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `recurring` boolean DEFAULT false;
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `recurring_interval` enum("daily", "weekly", "monthly", "quarterly", "annually");
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `related_entity_type` varchar(64);
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `related_entity_id` int;
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `created_at` timestamp NULL DEFAULT (now());
ALTER TABLE `tasks` ADD COLUMN IF NOT EXISTS `updated_at` timestamp NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `communicationStyle` enum("simple", "detailed", "expert") DEFAULT "detailed";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `responseLength` enum("concise", "standard", "comprehensive") DEFAULT "standard";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `responseFormat` varchar(64) DEFAULT "mixed";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `ttsVoice` varchar(64) DEFAULT "en-US-JennyNeural";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `autoPlayVoice` boolean DEFAULT false;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `handsFreeMode` boolean DEFAULT false;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `autoGenerateCharts` boolean DEFAULT true;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `riskTolerance` enum("conservative", "moderate", "aggressive");
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `financialGoals` json;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `taxFilingStatus` varchar(64);
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `stateOfResidence` varchar(64);
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `theme` enum("system", "light", "dark") DEFAULT "dark";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `sidebarDefault` enum("expanded", "collapsed") DEFAULT "expanded";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `chatDensity` enum("comfortable", "compact") DEFAULT "comfortable";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `language` varchar(64) DEFAULT "en";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `modelPreferences` json;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `ensembleWeights` json;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `temperature` float;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `maxTokens` int;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `customPromptAdditions` text;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `focusModeDefaults` varchar(128) DEFAULT "general,financial";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `thinkingDepth` enum("quick", "standard", "deep", "extended") DEFAULT "standard";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `creativity` float DEFAULT 0.7;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `contextDepth` enum("recent", "moderate", "full") DEFAULT "moderate";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `disclaimerVerbosity` enum("minimal", "standard", "comprehensive") DEFAULT "standard";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `autoFollowUp` boolean DEFAULT false;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `autoFollowUpCount` int DEFAULT 1;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `discoveryDirection` enum("deeper", "broader", "applied", "auto") DEFAULT "auto";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `discoveryIdleThresholdMs` int DEFAULT 120000;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `discoveryContinuous` boolean DEFAULT false;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `crossModelVerify` boolean DEFAULT false;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `citationStyle` enum("none", "inline", "footnotes") DEFAULT "none";
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `reasoningTransparency` boolean DEFAULT false;
ALTER TABLE `user_preferences` ADD COLUMN IF NOT EXISTS `customShortcuts` json;
