#!/usr/bin/env node
/**
 * Regenerate server/routers.ts to mount EVERY router file in server/routers/.
 * Reads each file, extracts the exported router name (matches `export const xxxRouter = router({` or `export const xxxRouter:` etc),
 * and emits a single appRouter mounting them all under their canonical key.
 *
 * Preserves the special hand-mounted routers (auth + system) and the @shared/const/getSessionCookieOptions imports.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROUTERS_DIR = path.resolve('server/routers');
const OUTPUT = path.resolve('server/routers.ts');

const files = fs.readdirSync(ROUTERS_DIR)
  .filter(f => f.endsWith('.ts') && !f.endsWith('.test.ts'))
  .sort();

// Each router file may export multiple named routers (e.g. stewardlySettings exports 5).
// We scan every file for `export const xxxRouter = router({` / `export const xxxRouter: ... = router({`.
const exports = []; // [{ file, exportName, mountKey }]
for (const f of files) {
  const text = fs.readFileSync(path.join(ROUTERS_DIR, f), 'utf8');
  // Match: export const xxxRouter = router(  OR  export const xxxRouter: ... = router(
  // We greedy-match so we catch "export const wealthEngineRouter = router({"
  const re = /export\s+const\s+([a-zA-Z_][a-zA-Z0-9_]*Router)\b[^=]*=\s*router\(/g;
  let m;
  while ((m = re.exec(text)) !== null) {
    const exportName = m[1];
    // mountKey is the export name without the trailing "Router".
    const mountKey = exportName.replace(/Router$/, '');
    exports.push({ file: f.replace(/\.ts$/, ''), exportName, mountKey });
  }
}

// Group exports by file (so we can do `import { a, b, c } from "./routers/file"`)
const byFile = new Map();
for (const e of exports) {
  if (!byFile.has(e.file)) byFile.set(e.file, []);
  byFile.get(e.file).push(e);
}

// De-duplicate mountKeys (some files may export both fooRouter + fooBarRouter; both get a unique key).
// Reserved/hand-mounted keys (auth + system) — exclude any router whose mountKey collides.
const RESERVED = new Set(['auth', 'system']);
const seenKeys = new Set();
const mounts = []; // [{ exportName, mountKey }]
for (const e of exports) {
  if (RESERVED.has(e.mountKey)) continue;
  if (seenKeys.has(e.mountKey)) {
    // suffix a number to disambiguate; should be rare
    let i = 2;
    while (seenKeys.has(`${e.mountKey}${i}`)) i++;
    e.mountKey = `${e.mountKey}${i}`;
  }
  seenKeys.add(e.mountKey);
  mounts.push(e);
}

// Sort by mountKey for deterministic output
mounts.sort((a, b) => a.mountKey.localeCompare(b.mountKey));

// Emit the file
let out = '';
out += `// AUTO-GENERATED by scripts/regen-routers.mjs — every router under server/routers/ is mounted.\n`;
out += `// Run \`node scripts/regen-routers.mjs\` after adding a new router file.\n`;
out += `\n`;

// Group imports by file for readability
const fileGroups = new Map();
for (const m of mounts) {
  if (!fileGroups.has(m.file)) fileGroups.set(m.file, []);
  fileGroups.get(m.file).push(m.exportName);
}
const sortedFiles = [...fileGroups.keys()].sort();
for (const f of sortedFiles) {
  const names = fileGroups.get(f).sort();
  out += `import { ${names.join(', ')} } from "./routers/${f}";\n`;
}

out += `import { COOKIE_NAME } from "@shared/const";\n`;
out += `import { getSessionCookieOptions } from "./_core/cookies";\n`;
out += `import { systemRouter } from "./_core/systemRouter";\n`;
out += `import { publicProcedure, router } from "./_core/trpc";\n`;
out += `\n`;
out += `export const appRouter = router({\n`;
out += `  system: systemRouter,\n`;
out += `  auth: router({\n`;
out += `    me: publicProcedure.query(opts => opts.ctx.user),\n`;
out += `    logout: publicProcedure.mutation(({ ctx }) => {\n`;
out += `      const cookieOptions = getSessionCookieOptions(ctx.req);\n`;
out += `      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });\n`;
out += `      return { success: true } as const;\n`;
out += `    }),\n`;
out += `  }),\n`;
for (const m of mounts) {
  out += `  ${m.mountKey}: ${m.exportName},\n`;
}
out += `});\n`;
out += `\n`;
out += `export type AppRouter = typeof appRouter;\n`;

fs.writeFileSync(OUTPUT, out, 'utf8');

console.log(`Wrote ${OUTPUT}`);
console.log(`Mounted ${mounts.length} routers from ${sortedFiles.length} files`);
console.log(`Total bytes: ${out.length}`);
