#!/usr/bin/env python3
"""Phase 3 tooling — diff column lists for the 3 overlap tables (`users`,
`tasks`, `user_preferences`).

For each overlap table, prints:
  - columns present in BOTH (must match — flagged for manual review if names
    are the same but the foundation type appears narrower than SAI's)
  - columns ONLY in SAI (must be added with ALTER TABLE)
  - columns ONLY in foundation (kept as-is — never dropped)

Output is saved to `migrations/inputs/overlap-column-diff.md` for inclusion
in the PR description and the runbook.
"""
from __future__ import annotations
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
FOUNDATION = REPO / "drizzle" / "schema.ts"
SAI = REPO / "migrations" / "inputs" / "sai-drizzle-schema.ts"
OUT = REPO / "migrations" / "inputs" / "overlap-column-diff.md"
OVERLAP = ["users", "tasks", "user_preferences"]


def parse_table_block(text: str, db_name: str) -> str | None:
    """Find the full TS block for `mysqlTable("<db_name>", { ... })...`"""
    m = re.search(rf'export const \w+ = mysqlTable\("{re.escape(db_name)}"\s*,\s*\{{', text)
    if not m:
        return None
    start = m.start()
    rest = text[m.end():]
    for pat in (r'\n[ \t]*\}\);\s*\n', r'\n[ \t]*\}\)\);\s*\n'):
        mm = re.search(pat, rest)
        if mm:
            return text[start : m.end() + mm.end()]
    return None


def parse_columns(block: str) -> list[tuple[str, str]]:
    """Return [(camelCase_name, sql_column_name)] for each column."""
    cols: list[tuple[str, str]] = []
    # Strip the (table) => ({...}) tail so we don't pick up index defs.
    body = block
    tail = re.search(r'\n\}\s*,\s*\(table\)\s*=>', body)
    if tail:
        body = body[: tail.start()]
    for m in re.finditer(
        r'^\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(?:[a-zA-Z]+(?:\s*<[^>]+>)?)\s*\(\s*"([^"]+)"',
        body,
        flags=re.MULTILINE,
    ):
        cols.append((m.group(1), m.group(2)))
    return cols


def render(table: str, found_cols: list[tuple[str, str]], sai_cols: list[tuple[str, str]]) -> str:
    found_sql = {c[1]: c[0] for c in found_cols}
    sai_sql = {c[1]: c[0] for c in sai_cols}
    both = sorted(set(found_sql) & set(sai_sql))
    only_sai = sorted(set(sai_sql) - set(found_sql))
    only_found = sorted(set(found_sql) - set(sai_sql))
    out = [f"## `{table}` overlap reconciliation\n"]
    out.append(f"- Columns in both: **{len(both)}** — kept as-is.")
    out.append(f"- Columns only in stewardly-ai: **{len(only_sai)}** — added via ALTER TABLE.")
    out.append(f"- Columns only in foundation: **{len(only_found)}** — preserved (never dropped).\n")
    if only_sai:
        out.append("### Added (`ALTER TABLE ... ADD COLUMN`)")
        for c in only_sai:
            out.append(f"- `{c}` (TS: `{sai_sql[c]}`)")
        out.append("")
    if only_found:
        out.append("### Preserved (foundation-only)")
        for c in only_found:
            out.append(f"- `{c}` (TS: `{found_sql[c]}`)")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> None:
    found_text = FOUNDATION.read_text()
    sai_text = SAI.read_text()
    parts = ["# Stewardly v3 overlap column reconciliation\n",
             "Generated by `migrations/scripts/02_diff_overlap_columns.py`. Per",
             "STEWARDLY v3 §6 the migration is **additive only** — overlap-table",
             "columns from the foundation are never dropped, and overlap-table",
             "columns from stewardly-ai are added as new columns alongside.\n"]
    for table in OVERLAP:
        fb = parse_table_block(found_text, table)
        sb = parse_table_block(sai_text, table)
        if not fb or not sb:
            parts.append(f"## `{table}`: skipped (table block not found)\n")
            continue
        fcols = parse_columns(fb)
        scols = parse_columns(sb)
        parts.append(render(table, fcols, scols))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts))
    print(f"Wrote {OUT}")
    print(OUT.read_text())


if __name__ == "__main__":
    main()
